#!/usr/bin/python
#
# Description: External STONITH module for openstack guests
#
# Author: Kim-Norman Sahm
# Email: kim-norman.sahm@t-online.de
# Licence: GPL
##################################################################

import sys
import os
import socket
from novaclient import client

global _debug
# Enable/disable debug mode
_debug = 0

if _debug:
	fobj = open("/var/log/stonith-openstack.log", "a")

argv = sys.argv
try:
    cmd = argv[1]
except IndexError:
    my_err("Not enough arguments")
    sys.exit(1)

if _debug:
	fobj.write(cmd + "\n")

xmlinfo = '''<parameters>
 <parameter name="openstack_instance" required="1">
  <content type="string"/>
  <shortdesc lang="en">openstack instance name</shortdesc>
  <longdesc lang="en">
   Contains the openstack instance (vm) name
  </longdesc>
 </parameter>
<parameter name="openstack_username" required="1">
  <content type="string"/>
  <shortdesc lang="en">openstack username</shortdesc>
  <longdesc lang="en">
   Contains the openstack username
  </longdesc>
 </parameter>
<parameter name="openstack_password" required="1">
  <content type="string" default=""/>
  <shortdesc lang="en">openstack password</shortdesc>
  <longdesc lang="en">
   The password for the openstack user
  </longdesc>
 </parameter>
<parameter name="openstack_tenant" required="1">
  <content type="string" default=""/>
  <shortdesc lang="en">openstack tenant (project) name</shortdesc>
  <longdesc lang="en">
   Contains the openstack tenant (project) name
  </longdesc>
 </parameter>
<parameter name="openstack_authurl" required="1">
  <content type="string" default=""/>
  <shortdesc lang="en">openstack authentication url (Keystone url)</shortdesc>
  <longdesc lang="en">
   Contains the openstack authentication url.
   Example: https://mycloud.example.com:5000/v2.0/
  </longdesc>
 </parameter>
<parameter name="openstack_poweraction" unique="0" required="0">
  <content type="string" default="reset"/>
  <shortdesc lang="en">Openstack power action method</shortdesc>
  <longdesc lang="en">
   Options:
   * reboot - soft reboot the instance
   * reboot-force  - hard reboot the instance
   * shutdown - shutdown the instance
  </longdesc>
 </parameter>

</parameters>'''


info = {
        'getinfo-xml':      xmlinfo,
	'getinfo-devdescr': 'OpenStack STONITH device',
	'getinfo-devid': 'OpenStack instance ' + socket.gethostname()
}

if cmd in info:
	print info[cmd]
	if _debug:
		fobj.write(info[cmd]+"\n")
	sys.exit(0)

if cmd == 'getconfignames':
	for arg in [ "openstack_instance", "openstack_username", "openstack_password", "openstack_tenant", "openstack_authurl", "openstack_poweraction"]:
		print arg	
	sys.exit(0)
    
### PLACEHOLDER - function must be created
if cmd == 'status':
	if _debug:
		fobj.write("Status = 0\n")
	sys.exit(0)

try:
	instance = os.environ.get('openstack_instance').split("=")[1]
except:
	try:
		instance = os.environ.get('openstack_instance')
	except:
		if _debug:
			for key in os.environ.keys():
	    			fobj.write("%30s %s \n" % (key,os.environ[key]))
try:
	username = os.environ.get('openstack_username').split("=")[1]
except:
	username = os.environ.get('openstack_username')
try:
	password = os.environ.get('openstack_password').split("=")[1]
except:
	 password = os.environ.get('openstack_password')
try:
	tenant = os.environ.get('openstack_tenant').split("=")[1]
except:
	tenant = os.environ.get('openstack_tenant')
try:
	authurl = os.environ.get('openstack_authurl').split("=")[1]
except:
	authurl = os.environ.get('openstack_authurl')
try:
	action =  os.environ.get('openstack_poweraction').split("=")[1]
except:
	action =  os.environ.get('openstack_poweraction')

if _debug:
	fobj.write("instance = " + instance+"\n")
	fobj.write("username = " + username+"\n")
	fobj.write("password = " + password+"\n")
	fobj.write("tenant = " + tenant+"\n")
	fobj.write("authurl = " + authurl+"\n")
	fobj.write("action = " + action+"\n")

if instance == "":
        print "ERROR - you must set a instance name"
        sys.exit(3)
elif username == "":
        print "ERROR - you must set your openstack username"
        sys.exit(3)
elif password == "":
        print "ERROR - you must set your openstack password"
        sys.exit(3)
elif tenant == "":
        print "ERROR - you must set your openstack tenant (project) name"
        sys.exit(3)
elif authurl == "":
        sys.exit(3)
        print "ERROR - you must set the authentication url (keystone url) from the openstack cloud"
        sys.exit(3)
elif action != "reboot" and action != "reboot-force" and action != "shutdown":
        print "ERROR - you must set a shutdown action (reboot, reboot-force or shutdown)"
        sys.exit(3)

if cmd == 'gethosts':
	print instance 
	if _debug:
	        fobj.write("gethosts = " + instance+"\n")
	sys.exit(0)

nova = client.Client(2, username, password, tenant, authurl)
found = 0
instances = nova.servers.list()
for vm in instances:
        if vm.name == instance:
                found = 1
                currentstatus = vm.status
                id = vm.id
                if _debug:
                        print "Found instance '" + instance +"' in tenant '" + tenant + "'"
                break
if found == 1:
	if _debug:
		print "Current state of instance '" + instance + "': " + currentstatus
else:
	print "ERROR - Cannot find any instance with name '" + instance + "'"
	sys.exit(3)

	

try:
       if action == "reboot":
                nova.servers.reboot(id,reboot_type='SOFT')
       elif action == "reboot-force":
                nova.servers.reboot(id,reboot_type='HARD')
       else:
                nova.servers.stop(id)
except:
        print "ERROR - Cannot shutdown instance '" + instance + "'"
        exit(4)

if _debug:
	fobj.close()


